apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: testing
  labels:
    name: frontend
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30001
  selector:
    name: frontend