apiVersion: v1
kind: ReplicationController
metadata: 
  name: frontend
  namespace: testing
  labels:
    name: frontend
spec:
  replicas: 3
  selector:
    name: frontend
  template:
    metadata:
      labels:
        name: frontend
    spec:
      containers:
        - name: frontend
          image: kubeguide/guestbook-php-frontend
          env:
            - name: GET_HOSTS_FROM
              value: env
          ports:
            - containerPort: 80
